title: Arch Linux installation instructions
author:
  name: Matteo Salonia
  email: matteo@salonia.it

description: >
  Arch Linux installation instructions

remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme

minima:
  skin: auto

social_links:
  - { platform: github,         user_url: "https://github.com/saloniamatteo/dotfiles" }
